export const products = [
    {
      id: 1,
      slug: "handmade-tribal-painting",
      title: "Handmade Tribal Painting",
      description: "A beautiful Rathwa tribal painting made with natural colors.",
      image: "/images/painting1.jpg",
      price: 1500,
      category: "Paintings",
      artisan: "Ramesh Rathwa",
      location: "Rajpipla, Gujarat",
    },
    {
      id: 2,
      slug: "traditional-clay-pot",
      title: "Traditional Clay Pot",
      description: "A handcrafted clay pot made by skilled artisans.",
      image: "/images/pot1.jpg",
      price: 800,
      category: "Pottery",
      artisan: "Sita Bhil",
      location: "Madhya Pradesh",
    },
    {
      id: 3,
      slug: "handwoven-textile",
      title: "Handwoven Textile",
      description: "A soft, colorful handwoven fabric made using tribal techniques.",
      image: "/images/textile1.jpg",
      price: 1200,
      category: "Textiles",
      artisan: "Govind Vasava",
      location: "Maharashtra",
    },
    {
      id: 4,
      slug: "handmade-tribal-painting",
      title: "Handmade Tribal Painting",
      description: "A beautiful Rathwa tribal painting made with natural colors.",
      image: "/images/painting1.jpg",
      price: 1500,
      category: "Paintings",
      artisan: "Ramesh Rathwa",
      location: "Rajpipla, Gujarat",
    },
    {
      id: 5,
      slug: "traditional-clay-pot",
      title: "Traditional Clay Pot",
      description: "A handcrafted clay pot made by skilled artisans.",
      image: "/images/pot1.jpg",
      price: 800,
      category: "Pottery",
      artisan: "Sita Bhil",
      location: "Madhya Pradesh",
    },
    {
      id: 6,
      slug: "handwoven-textile",
      title: "Handwoven Textile",
      description: "A soft, colorful handwoven fabric made using tribal techniques.",
      image: "/images/textile1.jpg",
      price: 1200,
      category: "Textiles",
      artisan: "Govind Vasava",
      location: "Maharashtra",
    },
    {
      id: 7,
      slug: "handmade-tribal-painting",
      title: "Traditional Clay Pot",
      description: "A handcrafted clay pot made by skilled artisans.",
      image: "/images/pot1.jpg",
      price: 800,
      category: "Pottery",
      artisan: "Sita Bhil",
      location: "Madhya Pradesh",
    },
    {
      id: 8,
      slug: "handwoven-textile",
      title: "Handwoven Textile",
      description: "A soft, colorful handwoven fabric made using tribal techniques.",
      image: "/images/textile1.jpg",
      price: 1200,
      category: "Textiles",
      artisan: "Govind Vasava",
      location: "Maharashtra",
    }
  ];