export const products = [
  {
    id: 1,
    slug: "handmade-tribal-painting",
    title: "Handmade Tribal Painting",
    description: "A beautiful Rathwa tribal painting made with natural colors.",
    image: "/images/products/painting.jpeg",
    price: 1500,
    category: "Paintings",
    artisan: "Ramesh Rathwa",
    location: "Rajpipla, Gujarat",
  },
  {
    id: 2,
    slug: "traditional-clay-pot",
    title: "Traditional Clay Pot",
    description: "A handcrafted clay pot made by skilled artisans.",
    image: "/images/products/1.jpeg",
    price: 800,
    category: "Pottery",
    artisan: "Sita Bhil",
    location: "Madhya Pradesh",
  },
  {
    id: 3,
    slug: "handwoven-textile",
    title: "Handwoven Textile",
    description: "A soft, colorful handwoven fabric made using tribal techniques.",
    image: "/images/products/Handwoven Textile.jpg",
    price: 1200,
    category: "Textiles",
    artisan: "Govind Vasava",
    location: "Maharashtra",
  },
  {
    id: 4,
    slug: "bamboo-handcrafted-basket",
    title: "Handcrafted Bamboo Basket",
    description: "A durable and eco-friendly basket made from natural bamboo.",
    image: "/images/products/Handcrafted Bamboo Basket.jpg",
    price: 600,
    category: "Handicrafts",
    artisan: "Manoj Nayak",
    location: "Assam",
  },
  {
    id: 5,
    slug: "wooden-tribal-mask",
    title: "Wooden Tribal Mask",
    description: "A stunning hand-carved tribal mask with intricate detailing.",
    image: "/images/products/Wooden Tribal Mask.jpg",
    price: 1800,
    category: "Woodwork",
    artisan: "Kishor Bhil",
    location: "Rajasthan",
  },
  {
    id: 6,
    slug: "terracotta-sculpture",
    title: "Terracotta Sculpture",
    description: "A beautifully crafted terracotta sculpture representing tribal art.",
    image: "/images/products/Terracotta Sculpture.jpg",
    price: 2200,
    category: "Sculptures",
    artisan: "Savita Rathore",
    location: "West Bengal",
  },
  {
    id: 7,
    slug: "warli-art-wall-hanging",
    title: "Warli Art Wall Hanging",
    description: "A unique wall hanging featuring traditional Warli tribal art.",
    image: "/images/products/Warli Art Wall Hanging.jpg",
    price: 1300,
    category: "Wall Art",
    artisan: "Anita Pawar",
    location: "Maharashtra",
  },
  {
    id: 8,
    slug: "handwoven-jute-bag",
    title: "Handwoven Jute Bag",
    description: "A stylish and eco-friendly handwoven jute bag for daily use.",
    image: "/images/products/Handwoven Jute Bag.jpg",
    price: 900,
    category: "Accessories",
    artisan: "Neha Das",
    location: "Tripura",
  },
  
];
